-- ASSIGNMENT ON EMP AND MANAGER RELATION :

-- 81.WAQTD SMITHS REPORTING MANAGER'S NAME


-- 82. WAQTD ADAMS MANAGER'S MANAGER NAME
-- 83.WAQTD DNAME OF JONES MANAGER
-- 84. WAQTD MILLER'S MANAGER'S SALARY
-- 85.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
-- 86. WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
-- 87.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
-- 88. WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
-- 89. WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
-- 90. WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER