-- ASSIGNMENT QUESTIONS ON GROUP BY :

-- 1.WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
	SELECT COUNT(*) AS NO_OF_EMP,DEPTNO
	FROM EMP
	WHERE JOB NOT IN 'PRESIDENT'
	GROUP BY DEPTNO;
-- 2.WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
 	SELECT SUM(SAL) AS TOTAL_SALARY,JOB
	FROM EMP
	GROUP BY JOB;
-- 3.WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN EACH DEPARTMENT .
	SELECT COUNT(*) AS NO_OF_EMP,DEPTNO
	FROM EMP
	WHERE JOB IN 'MANAGER'
	GROUP BY DEPTNO;

-- 4.WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE 
  EMPLOYEES OF DEPTNO 20.
	SELECT AVG(SAL)  AS AVG_SAL,DEPTNO
	FROM EMP
	WHERE DEPTNO NOT IN 20
	GROUP BY DEPTNO;

-- 5.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB .
	SELECT COUNT(*) AS NO_OF_EMP,JOB
	FROM EMP
	WHERE ENAME LIKE '%A%'
	GROUP BY JOB;

-- 6.WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
	SELECT COUNT(*) AS NO_OF_EMP,AVG(SAL) AS AVG_SAL,DEPTNO
	FROM EMP
	WHERE SAL>2000
	GROUP BY DEPTNO;

-- 7.WAQTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT.
	SELECT SUM(SAL) AS TOTAL_SAL,COUNT(JOB),DEPTNO
	FROM EMP
	WHERE JOB IN 'SALESMAN'
	GROUP BY DEPTNO;

-- 8.WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
	SELECT COUNT(*) AS NO_OF_EMP,MAX(SAL),JOB
	FROM EMP
	GROUP BY JOB;

-- 9.WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
	SELECT MAX(SAL),DEPTNO
	FROM EMP
	GROUP BY DEPTNO;

-- 10.WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE .
	SELECT COUNT(SAL) AS TIMES_SAL,SAL
	FROM EMP
	GROUP BY SAL;