
-- 11.WAQTD NUMBER OF EMPLOYEES HIRED ON THE SAME DAY INTO THE SAME DEPARTMENT SELECT COUNT(*) AS NO_OF_EMP,HIREDATE,DEPTNO
	FROM EMP
	GROUP BY DEPTNO,HIREDATE
	HAVING COUNT(*)>1;

-- 12.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT
	SELECT COUNT(*) AS NO_OF_EMP,SAL,DEPTNO
	FROM EMP
	GROUP BY SAL,DEPTNO
	HAVING COUNT(*)>1;

-- 13.WAQTD NUMBER OF EMPLOYEES HAVING THE SAME NAME IN THE SAME DEPARTMENT
	SELECT COUNT(*) AS NO_OF_EMP,ENAME,DEPTNO
	FROM EMP
	GROUP BY ENAME,DEPTNO
	HAVING COUNT(*)>1;

-- 14.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND HAVING THE SAME NAME .
	SELECT COUNT(*) AS NO_OF_EMP,SAL,DEPTNO,ENAME
	FROM EMP
	GROUP BY SAL,DEPTNO,ENAME
	HAVING COUNT(*)>1;

-- 15.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND HIRED ON THE SAME DAY .
	SELECT COUNT(*) AS NO_OF_EMP,SAL,DEPTNO,HIREDATE
	FROM EMP
	GROUP BY SAL,DEPTNO,HIREDATE
	HAVING COUNT(*)>1;