-- 1. WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SMITH
SELECT ENAME, SAL * 12 AS ANNUAL_SALARY 
FROM EMP 
WHERE ENAME = 'SMITH';

-- 2. WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK
SELECT ENAME 
FROM EMP 
WHERE JOB = 'CLERK';

-- 3.WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN
SELECT ENAME, SAL 
FROM EMP 
WHERE JOB = 'SALESMAN';

-- 4. WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000
SELECT * 
FROM EMP 
WHERE SAL > 2000;


-- 5. WAQTD DETAILS OF THE EMP WHOS NAME IS JONES.
SELECT * 
FROM EMP 
WHERE ENAME = 'JONES';

-- 6. WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81
SELECT * 
FROM EMP
WHERE HIREDATE > '01-JAN-81';

-- 7. WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000
SELECT ENAME, SAL, SAL * 12 AS ANNUAL_SALARY 
FROM EMP 
WHERE SAL * 12 > 12000;

-- 8.WAQTD EMPNO, ENAME OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30
SELECT EMPNO, ENAME 
FROM EMP 
WHERE DEPTNO = 30;

-- 9.WAQTD HIREDATE OF THE EMPLOYEES WORKING AS CLERK
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE JOB = 'CLERK';

-- 10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER.
SELECT * 
FROM EMP 
WHERE JOB = 'MANAGER';

-- 11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400.
SELECT ENAME, SAL 
FROM EMP 
WHERE COMM = 1400;

-- 12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY
SELECT * 
FROM EMP 
WHERE COMM > SAL;

-- 13.WAQTD HIREDATE OF JAMES
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE ENAME = 'JAMES';

-- 14. WAQTD DETAILS OF EMPLOYEES WORKING AS AN ANALYST.
SELECT * 
FROM EMP 
WHERE JOB = 'ANALYST';

-- 15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER 
SELECT * 
FROM EMP 
WHERE SAL > 2000;


-- 16. WAQTD NAMES OF THE EMPLOYEES WHO WERE HIRED BEFORE 1982.
SELECT ENAME 
FROM EMP 
WHERE HIREDATE < '01-JAN-82';

-- 17. WAQTD NAME, JOB, HIREDATE OF THE EMMPLOYEES HIRED AFTER 1999.
SELECT ENAME, JOB, HIREDATE 
FROM emp2 
WHERE HIREDATE > '01-JAN-1999';

-- 18. WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF THE ANNUAL SALARY OF THE EMPLOYEES IS LESS THAN 30,000
SELECT *, SAL * 12 AS ANNUAL_SALARY
FROM EMP
WHERE SAL * 12 < 30000;

-- 19. WAQTD NAME AND COMM OF THE EMPLOYEE EARNING 400 AS HIS COMM. 
SELECT ENAME, COMM 
FROM EMP 
WHERE COMM = 400;

-- 20. WAQTD NAME, JOB, SAL, COMM AND DEPTNO OF THE EMP WHO WAS HIRED BEFORE 14-NOV-1998.
SELECT ENAME, JOB, SAL, COMM, DEPTNO
FROM EMP
WHERE HIREDATE < '14-NOV-1998';
