-- special operators


-- 1. WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 10 OR 30
SELECT *
FROM emp
WHERE deptno IN (10, 30);

-- 2. WAQTD NAMES OF EMPLOYEES HIRED DURING 1982
SELECT ename
FROM emp
WHERE hiredate BETWEEN '01-JAN-82' AND '31-DEC-82';

-- 3. WAQTD NAME AND SALARY GIVEN TO THE EMPLOYEES EARNING COMMISSION
SELECT ename, sal
FROM emp
WHERE comm IS NOT NULL;

-- 4. WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1982 BUT BEFORE 1987
SELECT ename, hiredate
FROM emp
WHERE hiredate BETWEEN '01-JAN-83' AND '31-DEC-86';

5. WAQTD NAMES OF EMPLOYEES WHO EARN COMMISSION BUT NOT SALARY
SELECT ename
FROM emp
WHERE comm IS NOT NULL AND sal IS NULL;

-- 6. WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN AND DOSENT EARN ANY COMISSION 
SELECT *
FROM emp
WHERE job = 'SALESMAN' AND comm IS NULL;

-- 7. WAQTD NAME AND SALARY GIVEN TO THE EMPLOYEES HIRED DURING 1999 INTO DEPT 10 OR 40
SELECT ename, sal
FROM emp
WHERE hiredate BETWEEN '01-JAN-99' AND '31-DEC-99'
AND deptno IN (10, 40);

-- 8. LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
SELECT *
FROM emp
WHERE comm IS NULL;

-- 9. LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER
SELECT *
FROM emp
WHERE mgr IS NULL;

-- 10. LIST ALL THE SALESMEN IN DEPT 30
SELECT *
FROM emp
WHERE job = 'SALESMAN' AND deptno = 30;

-- 11. LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500
SELECT *
FROM emp
WHERE job IN 'SALESMAN' AND deptno IN 30 AND sal > 1500;

-- 12. LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT *
FROM emp
WHERE deptno NOT IN (10, 20);
 
-- 13. LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10
SELECT *
FROM EMP
WHERE mgr IS NOT NULL AND deptno IN 10;

-- 14. LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK
SELECT *
FROM emp
WHERE comm IS NULL AND job = 'CLERK';

-- 15. LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30
SELECT *
FROM emp
WHERE mgr IS NULL AND deptno IN (10, 30);

-- 16. LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
SELECT *
FROM emp
WHERE job IN 'SALESMAN' AND deptno IN 30 AND sal > 2450;

17. LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500 18.
LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30
19. DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81
20. DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB
21. LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 ΤΟ 3000.


-- ename starts with vowels
SELECT ename
FROM emp
where ename LIKe 'A%' 
OR ename LIKe 'E%' 
OR ename LIKe 'I%' 
OR ename LIKe 'O%' 
OR ename LIKe 'U%';

-- ename starts with consonants
SELECT ename
FROM emp
where ename NOT LIKe 'A%' 
OR ename NOT LIKe 'E%' 
OR ename NOT LIKe 'I%' 
OR ename NOT LIKe 'O%' 
OR ename NOT LIKe 'U%';


-- ename starts with vowels and ends with consonants
SELECT ename
FROM emp
WHERE ( ename LIKe 'A%' 
OR ename LIKe 'E%' 
OR ename LIKe 'I%' 
OR ename LIKe 'O%' 
OR ename LIKe 'U%') 
AND
(ename NOT LIKe '%A' 
OR ename NOT LIKe '%E' 
OR ename NOT LIKe '%I' 
OR ename NOT LIKe '%O' 
OR ename NOT LIKe '%U');