-- EXTRA QUESTIONS ON SUBQUERY:

-- 81.WAQTD DNAME IN WHICH THERE ARE ATLEAST 5 EMPLOYEES WORKING

-- 82.WAQTD LOC IN WHICH THERE ARE EXACTLY 3 EMPLOYEES WORKING
-- 83.WAQTD DETAILS OF THE EMPLOYEES EARNING SAME SALARY
-- 84.WAQTD SALARIES OF THE EMPLOYEES HAVING SAME NAMES
-- 85.WAQTD DETAILS OF THE EMPLOYEES GETTING SAME SALARY IN THE SAME DEPARTMENT
-- 86. WAQTD DETAILS OF THE EMPLOYEES HIRED ON THE SAME DAY INTO THE SAME DEPARTMENT
-- 87.WAQTD NAME AND SAL OF THE EMPLOYEES IF THEIR NAME IS REPEATED ATLEST 4 TIMES IN EMPLOYEE TABLE
-- 88. WAQTD DETAILS OF THE EMPLOYEES HAVING SAME DESIGNATIONS IN THE SAME DEPARTMENT.
-- 89.WAQTD DETAILS OF THE EMPLOYEES HAVING SAME NAMES IN THE SAME JOB
-- 90.WAQTD DETAILS OF THE EMPLOYEE TO WHOM ATLEST 3 EMPLOYEES REPORT.
-- OR
-- WAQTD DETAILS OF THE EMPLOYEE HAVING ATLEST 3 REPORTINGS