-- EXTRA QUESTIONS ON SUBQUERY:

-- 81.WAQTD DNAME IN WHICH THERE ARE ATLEAST 5 EMPLOYEES WORKING
SELECT dname
FROM dept
WHERE deptno IN (
    SELECT deptno
    FROM emp
    GROUP BY deptno
    HAVING COUNT(deptno) >= 5
);

-- 82.WAQTD LOC IN WHICH THERE ARE EXACTLY 3 EMPLOYEES WORKING
select loc
from dept
where deptno in(select deptno
from emp
group by deptno
having count(deptno)=3); 

-- 83.WAQTD DETAILS OF THE EMPLOYEES EARNING SAME SALARY
select *
from emp
where sal = ANY (select sal
from emp
group by sal
having count(sal)>=2
);

-- 84.WAQTD SALARIES OF THE EMPLOYEES HAVING SAME NAMES
SELECT ENAME, SAL
FROM EMP
WHERE ENAME IN (
    SELECT ENAME
    FROM EMP
    GROUP BY ENAME
    HAVING COUNT(ENAME) > 1
);

-- 85.WAQTD DETAILS OF THE EMPLOYEES GETTING SAME SALARY IN THE SAME DEPARTMENT
SELECT * 
FROM EMP
WHERE (SAL, DEPTNO) IN (
    SELECT SAL, DEPTNO
    FROM EMP
    GROUP BY SAL, DEPTNO
    HAVING COUNT(*) > 1
);

-- 86. WAQTD DETAILS OF THE EMPLOYEES HIRED ON THE SAME DAY INTO THE SAME DEPARTMENT
SELECT * 
FROM EMP
WHERE (HIREDATE, DEPTNO) IN (
    SELECT HIREDATE, DEPTNO
    FROM EMP
    GROUP BY HIREDATE, DEPTNO
    HAVING COUNT(*) > 1
);

-- 87.WAQTD NAME AND SAL OF THE EMPLOYEES IF THEIR NAME IS REPEATED ATLEST 4 TIMES IN EMPLOYEE TABLE
SELECT ENAME, SAL
FROM EMP
WHERE ENAME IN (
    SELECT ENAME
    FROM EMP
    GROUP BY ENAME
    HAVING COUNT(ENAME) >= 4
);

-- 88. WAQTD DETAILS OF THE EMPLOYEES HAVING SAME DESIGNATIONS IN THE SAME DEPARTMENT.
SELECT *
FROM EMP
WHERE (JOB, DEPTNO) IN (
    SELECT JOB, DEPTNO
    FROM EMP
    GROUP BY JOB, DEPTNO
    HAVING COUNT(*) > 1
);

-- 89.WAQTD DETAILS OF THE EMPLOYEES HAVING SAME NAMES IN THE SAME JOB
SELECT *
FROM EMP
WHERE (JOB, ENAME) IN (
    SELECT JOB, ENAME
    FROM EMP
    GROUP BY JOB, ENAME
    HAVING COUNT(*) > 1
);

-- 90.WAQTD DETAILS OF THE EMPLOYEE TO WHOM ATLEST 3 EMPLOYEES REPORT.
-- OR
-- WAQTD DETAILS OF THE EMPLOYEE HAVING ATLEST 3 REPORTINGS
SELECT * 
FROM EMP
WHERE EMPNO IN (
    SELECT MGR
    FROM EMP
    GROUP BY MGR
    HAVING COUNT(MGR) >= 3
);