-- Q.WAQTD EMPLOYEE NAME ENDING WITH CONSEQUATIVE 'T'?
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME,-2) = 'TT';

-- Q.WAQTD EMPLOYEE NAME WHO'S LAST 2ND CHAR IS 'E'?
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME,-2,1) = 'E';

-- Q. WAQTD EMPLOYEE NAME WHO'S FIRST CHAR AND LAST CHAR BOTH ARE SAME ?
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME,1,1) = SUBSTR(ENAME,-1);

-- Q.WAQ TO EXTRACT FIRST 3 CHARACTERS FROM ALL THE EMPLOYEE NAMES ?
SELECT SUBSTR(ENAME,1,3) AS FIRST_3_CHARS
FROM EMP;

-- Q. WAQ TO EXTRACT FIRST HALF NAMES FROM EMPLOYEE NAMES ?
SELECT SUBSTR(ENAME,1,LENGTH(ENAME)/2) AS HALF_NAME
FROM EMP;

-- Q. WAQ TO EXTRACT SECOND HALF NAMES FROM EMPLOYEE NAME?
SELECT SUBSTR(ENAME,(LENGTH(ENAME)/2)+1) AS HALF_NAME
FROM EMP;

-- Q. WAQTD EMPLOYEE NAME STARTS WITH VOWELS ?
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME,1,1) IN ('A','E','O','I','U');

-- Q. WAQTD EMPLOYEE NAME STARTS WITH CONSONENTS AND END WITH VOWELS ?
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME,1,1) NOT IN ('A','E','O','I','U')
AND SUBSTR(ENAME,-1) IN ('A','E','O','I','U');